In [17]:
import pandas as pd
import numpy as np
from scipy.stats import mstats

# Load the dataset with the correct semicolon separator
df = pd.read_csv('/content/housing_dirty.csv', sep=';')

# Display the first few rows to verify
display(df.head())

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1   2970.0     10840.0  jogja   20.0          2000    baik
1   2   2540.0      7610.0  Medan    NaN          1995   Bagus
2   3   2497.0      8950.0  Depok    NaN          1983    baik
3   4    497.0      1780.0    YGY   50.0          2013    baik
4   5   1334.0      4240.0  Medan   50.0          2004  Sedang

In [18]:
# STEP 0 — Load & eksplorasi awal
df = pd.read_csv('housing_dirty.csv', sep=';')
print('Shape awal:', df.shape)
print(df.isnull().sum())

Shape awal: (130, 7)
id               0
luas_m2         18
harga_juta      17
kota             0
kamar           10
tahun_bangun     0
kondisi          0
dtype: int64

In [19]:
# STEP 1 — Hapus Duplikat
df.drop_duplicates(inplace=True)
print('Setelah hapus duplikat:', df.shape)

Setelah hapus duplikat: (130, 7)

In [20]:
# STEP 2 — Normalisasi String
df['kota'] = df['kota'].str.strip().str.title()
df['kondisi'] = df['kondisi'].str.strip().str.lower()

In [21]:
# STEP 3 — Imputasi Missing Values
df['luas_m2'] = df['luas_m2'].fillna(df['luas_m2'].median())
df['harga_juta'] = df['harga_juta'].fillna(df['harga_juta'].median())
df['kamar'] = df['kamar'].fillna(df['kamar'].mode()[0])

In [22]:
# STEP 4 — Tangani Outlier (IQR Fence)
for col in ['harga_juta', 'luas_m2', 'tahun_bangun']:
    Q1, Q3 = df[col].quantile([0.25, 0.75])
    IQR = Q3 - Q1
    df[col] = df[col].clip(Q1-1.5*IQR, Q3+1.5*IQR)

In [23]:
# STEP 5 — Validasi & Ekspor
assert df.isnull().sum().sum() == 0, 'Masih ada missing!'
assert df.duplicated().sum() == 0, 'Masih ada duplikat!'
print('Shape akhir:', df.shape)
df.to_csv('housing_clean.csv', index=False)
print('Dataset bersih tersimpan!')

Shape akhir: (130, 7)
Dataset bersih tersimpan!

### STEP 6 — Akses API JSONPlaceholder
Tahap terakhir adalah mengambil data dari API publik dan mengonversinya ke dalam DataFrame.

In [15]:
import pandas as pd
import requests

# Mengambil data dari JSONPlaceholder (contoh: endpoint /posts)
url = 'https://jsonplaceholder.typicode.com/posts'
response = requests.get(url)

# Cek apakah request berhasil
if response.status_code == 200:
    data_api = response.json()
    df_api = pd.DataFrame(data_api)
    print('Berhasil mengambil data dari API!')
    display(df_api.head())
else:
    print(f'Gagal mengambil data. Status code: {response.status_code}')

Berhasil mengambil data dari API!

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [24]:
import pandas as pd

# Mengatur agar pandas menampilkan semua baris
pd.set_option('display.max_rows', 150)

# Menampilkan seluruh dataset
display(df)

      id  luas_m2  harga_juta        kota  kamar  tahun_bangun         kondisi
0      1  2970.00     10840.0       Jogja   20.0        2000.0            baik
1      2  2540.00      7610.0       Medan   10.0        1995.0           bagus
2      3  2497.00      8950.0       Depok   10.0        1983.0            baik
3      4   497.00      1780.0         Ygy   50.0        2013.0            baik
4      5  1334.00      4240.0       Medan   50.0        2004.0          sedang
5      6  1533.00      8140.0     Jakarta   10.0        2006.0          sedang
6      7  1143.00      6550.0     Jakarta   30.0        2011.0            baik
7      8  1938.00      3330.0  Yogyakarta   10.0        1989.0     baik sekali
8      9   812.00      3070.0  Yogyakarta   10.0        1996.0          sedang
9     10   691.00      2370.0     Bandung   50.0        1980.0            baik
10    11  1596.00      6300.0    Surabaya   60.0        2023.0          sedang
11    12   812.00      3450.0         Dpk   50.0        2008.0            baik
12    13   842.00      3820.0         Sby   20.0        2006.0          sedang
13    14  1938.00      8020.0     Jakarta   30.0        2004.0            baik
14    15  1938.00      5030.0    Makassar   60.0        2016.0          sedang
15    16  2005.00      4950.0         Mdn   60.0        1994.0            baik
16    17  3033.00     10430.0     Bandung   40.0        1993.0          sedang
17    18   515.00      1830.0  Yogyakarta   60.0        2020.0          sedang
18    19  1938.00      6550.0     Bandung   10.0        2015.0           rusak
19    20  2977.00      6550.0    Surabaya   10.0        2009.0            baik
20    21  1950.00      5110.0       Medan   10.0        2014.0          sedang
21    22  1938.00      6550.0    Semarang   20.0        1984.0            baik
22    23  3009.00      6550.0    Semarang   50.0        2000.0            baik
23    24   534.00      1560.0       Medan   40.0        2002.0          sedang
24    25   977.00      3490.0  Yogyakarta   50.0        1995.0          sedang
25    26  1938.00      9160.0    Semarang   40.0        2013.0     baik sekali
26    27  1138.00     -4227.5     Bandung   60.0        1993.0     baik sekali
27    28  2488.00      9550.0  Yogyakarta   60.0        1993.0            baik
28    29  2263.00      6640.0       Medan   30.0        2016.0            baik
29    30  1103.00      4550.0  Yogyakarta   60.0        1986.0            baik
30    31  1894.00      8190.0       Jogja   60.0        2012.0          sedang
31    32   679.00      1950.0    Makassar   20.0        1980.0           rusak
32    33   774.00      2370.0       Medan   50.0        2007.0           cukup
33    34  2886.00     15980.0     Jakarta   40.0        2016.0           rusak
34    35  2949.00      9340.0       Medan   40.0        2017.0            baik
35    36  2784.00      8630.0       Medan   10.0        2021.0          sedang
36    37  1938.00      6310.0         Smg   40.0        1996.0          sedang
37    38   404.00      1700.0         Ygy   60.0        2005.0            baik
38    39   691.00      2370.0     Bandung   50.0        1980.0            baik
39    40  2441.00      6650.0    Makassar   30.0        2004.0     baik sekali
40    41  1254.00      7350.0     Jakarta   40.0        1990.0            baik
41    42  1932.00      6410.0     Bandung   10.0        2004.0          sedang
42    43  2232.00         0.0       Medan   60.0        1993.0          sedang
43    44  3436.00     16870.0     Jakarta   30.0        2011.0            baik
44    45  2801.00     10080.0    Semarang   60.0        2005.0          sedang
45    46  2606.00      9740.0       Depok   50.0        2003.0            baik
46    47  1358.00      5220.0         Bdg   10.0        1999.0            baik
47    48  1533.00      4220.0    Makassar   10.0        2008.0          sedang
48    49  2924.00     13230.0    Surabaya   40.0        2019.0           rusak
49    50   930.00      6550.0     Bandung   30.0        2010.0           rusak
50    51  1259.00      7510.0     Jakarta   50.0        1985.0           cukup
51    52   523.00      2080.0  Yogyakarta   20.0        1989.0          sedang
52    53  1938.00      9160.0       Jogja   10.0        2005.0          sedang
53    54  3252.00      7830.0    Makassar   20.0        2011.0            baik
54    55  1944.00      4560.0    Makassar   10.0        2013.0          sedang
55    56   703.00      1810.0    Makassar   40.0        1985.0          sedang
56    57  2027.00      7460.0       Depok   60.0        2017.0            baik
57    58  1938.00     10710.0       Jogja   40.0        1997.0            baik
58    59  1938.00      6550.0    Surabaya   20.0        2018.0            baik
59    60  2977.00     12500.0    Surabaya   10.0        2009.0            baik
60    61  2705.00      8800.0     Bandung   50.0        2020.0            baik
61    62  1938.00      4950.0       Medan   60.0        1994.0     baik sekali
62    63  1697.00      5320.0       Medan   10.0        1994.0          sedang
63    64  1334.00      5060.0     Bandung   30.0        1998.0           rusak
64    65   801.00      3150.0  Yogyakarta   10.0        1991.0            baik
65    66  1117.00      4570.0       Depok   50.0        1998.0     baik sekali
66    67  1938.00      6550.0       Medan   40.0        2022.0          sedang
67    68   416.00      6550.0    Makassar   10.0        1981.0            baik
68    69  1184.00      6550.0     Jakarta   40.0        1981.0            baik
69    70  3290.00      9120.0       Medan   50.0        2002.0            baik
70    71  1944.00      4560.0    Makassar   10.0        2013.0          sedang
71    72  2027.00      7460.0         Dpk   60.0        2017.0            baik
72    73  1938.00      8940.0     Bandung   60.0        1960.5  perlu renovasi
73    74  2964.00     14060.0       Depok   10.0        1982.0           cukup
74    75   569.00      1760.0    Semarang   20.0        1999.0          sedang
75    76  2824.00     10770.0     Bandung   10.0        2001.0          sedang
76    77  3084.00     10050.0     Bandung   20.0        1987.0           rusak
77    78   438.00      1390.0       Medan   10.0        2017.0            baik
78    79  2407.00      9870.0       Jogja   50.0        2001.0            baik
79    80  1938.00     17192.5     Jakarta   20.0        1986.0          sedang
80    81  3264.00     14920.0       Depok   50.0        2020.0          sedang
81    82  3085.00     12040.0    Surabaya   50.0        1982.0            baik
82    83  2351.00      6550.0        Mksr   10.0        2012.0            baik
83    84  2185.00      6960.0     Bandung   20.0        2042.5          sedang
84    85   749.00      3040.0  Yogyakarta   50.0        1995.0            baik
85    86  -500.00      3450.0       Depok   50.0        2008.0            baik
86    87   987.00      5750.0     Jakarta   10.0        1988.0           bagus
87    88  2377.00     14680.0     Jakarta   30.0        2016.0           cukup
88    89  2242.00      6910.0    Semarang   20.0        1984.0           bagus
89    90  1667.00      6550.0       Jogja   10.0        1997.0            baik
90    91   723.00      6550.0       Jogja   30.0        2009.0            baik
91    92  2103.00      8180.0       Depok   20.0        2002.0            baik
92    93  1938.00      4550.0  Yogyakarta   10.0        1986.0            baik
93    94  3108.00      7670.0    Makassar   30.0        1998.0           cukup
94    95  2254.00      6550.0       Depok   10.0        1983.0           bagus
95    96  3436.00     16870.0     Jakarta   30.0        2011.0            baik
96    97  1352.00      3800.0       Medan   10.0        1989.0          sedang
97    98  2680.00     15250.0     Jakarta   40.0        2007.0          sedang
98    99  3106.00     11480.0     Bandung   10.0        2005.0          sedang
99   100  1676.00      5290.0     Bandung   50.0        2015.0            baik
100  101  2885.00     10230.0    Semarang   10.0        1998.0            baik
101  102  2216.00     17192.5       Medan   40.0        2022.0          sedang
102  103  1785.00      6550.0         Mdn   30.0        2042.5          sedang
103  104  5129.75      1790.0         Ygy   40.0        1985.0           bagus
104  105  3194.00      9430.0    Semarang   40.0        1987.0            baik
105  106  2702.00      6770.0       Medan   30.0        2012.0     baik sekali
106  107  1103.00      2470.0        Mksr   40.0        1982.0          sedang
107  108  3412.00     13570.0         Sby   60.0        2010.0            baik
108  109  1655.00      6960.0    Surabaya   20.0        1992.0            baik
109  110   657.00      6550.0    Makassar   10.0        1993.0            baik
110  111  2227.00      5950.0    Makassar   40.0        2016.0            baik
111  112  3273.00     11460.0    Surabaya   40.0        2022.0            baik
112  113  1938.00     10910.0     Bandung   40.0        1987.0           rusak
113  114   671.00      2100.0       Medan   30.0        2003.0           jelek
114  115   528.00      2060.0  Yogyakarta   20.0        2002.0            baik
115  116  2862.00      6340.0    Makassar   10.0        1983.0          sedang
116  117  1938.00      1710.0    Makassar   60.0        2001.0           rusak
117  118  3394.00     13840.0    Surabaya   10.0        1990.0            baik
118  119  3361.00     13820.0    Surabaya   10.0        2019.0           jelek
119  120   908.00      6550.0  Yogyakarta   50.0        1996.0           rusak
120  121   693.00      2310.0       Jogja   20.0        2002.0           rusak
121  122   819.00      3490.0       Depok   60.0        2011.0            baik
122  123   743.00      2470.0         Smg   30.0        1990.0           bagus
123  124   772.00      2580.0  Yogyakarta   40.0        2003.0            baik
124  125  1608.00      4550.0    Makassar   40.0        2002.0           rusak
125  126  3302.00     10500.0    Semarang   60.0        1993.0            baik
126  127  1938.00      6550.0    Makassar   50.0        2008.0            baik
127  128   841.00      2020.0    Makassar   20.0        1986.0            baik
128  129   880.00      2520.0    Makassar   10.0        1986.0           bagus
129  130  2154.00      9410.0  Yogyakarta   10.0        2013.0           cukup